//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katherine_Patino_Arellana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Cliente = new HashSet<Cliente>();
        }

        [Display(Name = "#")]
        public int Id { get; set; }

        [Display(Name = "Nombre de la Ciudad")]
        public string Nombre { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
