//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katherine_Patino_Arellana.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [Display(Name = "#")]
        public int Id { get; set; }
        [Display(Name = "Rut Cliente")]
        public string Rut { get; set; }
        [Display(Name = "Razon Social")]
        public string razonSocial { get; set; }
        [Display(Name = "Ciudad")]
        public Nullable<int> CiudadId { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}
